// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT-v-URLx5YPuGoYxdOCe1Jki-Toxc1u8',
    appId: '1:322325479334:web:51688b07e2825da6261967',
    messagingSenderId: '322325479334',
    projectId: 'campus-event-df7db',
    authDomain: 'campus-event-df7db.firebaseapp.com',
    storageBucket: 'campus-event-df7db.firebasestorage.app',
    databaseURL: 'https://campus-event-df7db-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJDLvZJft0tnxVfP8uvJwy5SgvjEVs8u4',
    appId: '1:322325479334:android:d9b2d18917c6f325261967',
    messagingSenderId: '322325479334',
    projectId: 'campus-event-df7db',
    storageBucket: 'campus-event-df7db.firebasestorage.app',
    databaseURL: 'https://campus-event-df7db-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEZzQu8jx9Ki7iagQP_V-YCHmaAJ-E560',
    appId: '1:322325479334:ios:fad77b9157372e58261967',
    messagingSenderId: '322325479334',
    projectId: 'campus-event-df7db',
    storageBucket: 'campus-event-df7db.firebasestorage.app',
    databaseURL: 'https://campus-event-df7db-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosBundleId: 'com.example.campusEvent',
  );
}